### PR TITLE
Adding Firefox and Sauce karma launchers.

### PR DESCRIPTION
**Pull request by anthonymayer**
Note: The Sauce launcher won't work correctly until more config options are added.

### CODE REVIEW

**Comment by Sanjo** [comment]
My todos:

* [ ] Release new sanjo:karma version
* [ ] Depend on new sanjo:karma version

**Comment by anthonymayer** [comment]
Any idea when you'll get to those? I tested it and the Firefox runner definitely works on travis so I'd love to use it asap. Thanks!

**Comment by anthonymayer** [comment]
bump

**Comment by Sanjo** [comment]
Firefox is now available in 0.11.0. Thanks for reminding me.

**Comment by anthonymayer** [comment]
Thanks!

**Pull request merged**
